### ISSUE TITLE
use evalpoly to inline polynomial evaluations

### ISSUE THREAD

**Issue by stevengj** [EP-Guy/ModifiedHankelFunctionsOfOrderOneThird#18]
I notice that you are using explicit loops to evaluate your series approximations; if you use the `@evalpoly` macro (or the `evalpoly` function in Julia 1.6 with a tuple argument), you can have the compiler inline these…

**Comment by fgasdia** [comment]
@stevengj thanks for the tip. I've merged code using evalpoly and the functions are ~20-25% faster.
